import { AlertTriangle, CircuitBoard, MessageSquarePlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ChatComposer } from "@/components/console/ChatComposer";
import { MessageList } from "@/components/console/MessageList";
import { PersonaDock } from "@/components/console/PersonaDock";

export default function ChatPage({
  personas,
  settings,
  activeConversation,
  messages,
  selectedPersona,
  setSelectedPersona,
  loading,
  booting,
  error,
  onSendMessage,
  onNewConversation,
}) {
  const endpointReady = Boolean(settings?.endpoint_url);

  return (
    <div className="page-grid chat-page" data-testid="chat-page">
      <section className="chat-column" data-testid="chat-column">
        <header className="page-header" data-testid="chat-page-header">
          <div>
            <p className="eyebrow" data-testid="chat-page-eyebrow">OPENAI-COMPATIBLE GGUF ROUTE</p>
            <h2 data-testid="chat-page-title">{activeConversation?.title || "Live Signal Console"}</h2>
          </div>
          <Button className="neo-button compact" onClick={onNewConversation} data-testid="chat-new-conversation-button">
            <MessageSquarePlus size={15} /> NEW
          </Button>
        </header>

        {error && (
          <div className="error-banner" data-testid="chat-error-banner">
            <AlertTriangle size={16} /> <span data-testid="chat-error-message">{error}</span>
          </div>
        )}

        <MessageList messages={messages} loading={loading} booting={booting} />
        <ChatComposer disabled={loading || !endpointReady} endpointReady={endpointReady} onSendMessage={onSendMessage} />
      </section>

      <aside className="right-rail" data-testid="chat-right-rail">
        <section className="endpoint-card" data-testid="endpoint-summary-card">
          <div className="section-head" data-testid="endpoint-summary-heading">
            <CircuitBoard size={14} /> CONNECTION
          </div>
          <div className="server-visual" data-testid="server-visual" />
          <p className="endpoint-state" data-testid="endpoint-state-text">{endpointReady ? "ROUTE CONFIGURED" : "ROUTE REQUIRED"}</p>
          <code data-testid="endpoint-url-summary">{settings?.endpoint_url || "No endpoint saved"}</code>
        </section>
        <PersonaDock personas={personas} selectedPersona={selectedPersona} setSelectedPersona={setSelectedPersona} />
        <p className="disclaimer" data-testid="usage-disclaimer">
          Model output is generated by your configured llama-server. Review responses before relying on them.
        </p>
      </aside>
    </div>
  );
}